import Head from 'next/head';
import { useRouter } from 'next/router';
import React from 'react';
import Accordion from '../components/seoAccordion';
import Button from '../components/Button';
import Cta from '../components/Cta';
import Div from '../components/Div';
import IconBox from '../components/IconBox';
import Layout from '../components/Layout';
import PageHeading from '../components/PageHeading';
import SectionHeading from '../components/SectionHeading';
import Spacing from '../components/Spacing';
import { Icon } from '@iconify/react';
import Image from 'next/image';
import PricingTableList from '../components/PricingTable/PricingTableListSeo';
import MovingText2 from '../components/MovingText/MovingText2'
import seo1 from '../public/images/icons/seo1.svg'
import seo2 from '../public/images/icons/seo2.svg'
import seo3 from '../public/images/icons/seo3.svg'
import hero from '../public/images/seohero.webp'
import mnml from '../public/images/icons/jp16mnmlseo.jpg'
import graphic from '../public/images/seographic.webp'
import contactbg from '../public/images/contactbg.webp'

export default function ServiceDetails() {
  const router = useRouter();
  const serviceId = router.query.serviceId;

  const serviceData2 = [
    {
      title: 'SEO',
      href: '/seo-services',
    },
    {
      title: 'Digital Marketing',
      href: '/digital-marketing',
    },
    {
      title: 'Web Design',
      href: '/web-design',
    },
  ];
  
  return (
    <>
      <Head>
        <title>SEO Services - JP16</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
      <PageHeading 
        title='Professional SEO Services'
        bgSrc={hero.src}
        pageLinkText='seo-services'
      />
      <Spacing lg='145' md='80'/>
      <Div className="container">
        <SectionHeading 
          title='Our SEO Process' 
          subtitle="Optimal visibility at every step of the buyer journey." 
          variant='cs-style1 text-center'
        />
        <Spacing lg='90' md='45'/>
        <Div className="row">
          <Div className="col-lg-4">
            <IconBox
              icon={seo1.src}
              title='Keyword Research'
              subtitle="In order to attract more organic traffic to your website, you need to know what keywords your target audience is searching for. Keyword research is the process of analyzing popular search terms and identifying the ones that are most relevant to your business. With the help of professional SEO services, you can find the perfect keywords to target and create content around."
            />
            <Spacing lg='30' md='30'/>
          </Div>
          <Div className="col-lg-4">
            <IconBox
              icon={seo2.src}
              title='On-Page Optimization'
              subtitle="On-page optimization involves optimizing the elements on your website to make them more search engine friendly. This includes optimizing page titles, meta descriptions, and header tags, as well as ensuring that your website is mobile-friendly and has fast loading times. By optimizing your website for search engines, you can improve your search engine rankings and attract more organic traffic."
            />
            <Spacing lg='30' md='30'/>
          </Div>
          <Div className="col-lg-4">
            <IconBox
              icon={seo3.src}
              title='Link Building'
              subtitle="Building high-quality backlinks is one of the most important factors in improving your website's authority and search engine rankings. Professional SEO services can help you build a backlink profile that includes links from high-quality, authoritative websites in your industry. With the help of professional SEO services, you can build a strong backlink profile and improve your search engine rankings."
            />
            <Spacing lg='30' md='30'/>
          </Div>
        </Div>
      </Div>
      <Spacing lg='120' md='50'/>
      <Div className="container">
        <Div className="row align-items-center">
          <Div className="col-xl-5 col-lg-6">
            <Div className="cs-radius_15 cs-shine_hover_1">
             <Image src={mnml.src} alt="Service2" className='cs-radius_15 w-100 cs-hidden_mobile' width={800} height={600} />
            </Div>
            <Spacing lg='0' md='40'/>
          </Div>
          <Div className="col-lg-6 offset-xl-1">
            <Spacing lg='0' md='45'/>
            <Div className="cs-section_heading cs-style1">
              <h2 className="cs-section_title">SEO: It's All About Return on Investment</h2>
              <Div className="cs-height_5 cs-height_lg_5" />
              <Div className="cs-separator cs-accent_bg" />
              <Div className="cs-height_45 cs-height_lg_25" />
              <p className="cs-m0">Underquoting an SEO client is a surefire way to get the worst possible return on investment. This is due to the fact that SEO is a never-ending competition. It’s a search engine ranking race where the goal isn’t just to finish first, but to stay at the front of the pack and influence those behind you.

Assuming there are many people ahead of you, it is critical to understand how fast you must run to beat the competition. You will never catch up if you keep running at the same pace.

Your SEO investment is what determines your speed and ranking. You want to be able to run faster? Increase your investment! More money equals more time. The more time you spend, similar to a personal trainer, the more progress you will see.

How are you supposed to outperform those who invest $2500 per month if you only invest $200 per month? You simply cannot. It is critical to calculate work based on your speed in order to ensure consistent results.

If you invested $2000 per month, you could open up many revenue streams and strategically position yourself at the top of Google. You would have an excellent return on investment with active leads and an additional $10,000 – $50,000 coming in.</p>
              <Div className="cs-height_45 cs-height_lg_30" />
              <Spacing lg='45' md='45'/>
              <Div className="col-sm-12">
              {/* <Button btnLink='/service/service-details' btnText='Web page design' variant='cs-type2'/> */}
                  <Button btnLink='/contact' btnText='Contact Us Today For a Free Consultation!' variant='cs-type'>
                    <Icon icon="bi:arrow-right" />
                  </Button>
                </Div>
            </Div>
          </Div>
        </Div>
      </Div>

      <Spacing lg='150' md='40'/>
      <Div className="container">
        <Div className="row align-items-center">
          <Div className="col-xl-6 col-lg-6">
            <Div className="cs-section_heading cs-style1">
              <h2 className="cs-section_title">If You Want a $200/Month SEO Company, Then We're Not a Great Fit</h2>
              <Div className="cs-height_5 cs-height_lg_5" />
              <Div className="cs-separator cs-accent_bg" />
              <Div className="cs-height_45 cs-height_lg_25" />
              <p className="cs-m0">As you now know, it is essential to allocate the funds necessary for an SEO budget to grow your online business. We simply do not onboard people who do not recognize the significance of this principle for this reason. We won’t be able to get a good return on investment with a budget of $4, $5, or $600 per month. Over the years, we have witnessed the favorable impact that an effective SEO strategy can have on a business and the level of happiness it can generate. On the other hand, we’ve seen the ineffectiveness of a lackluster SEO strategy, as well as the mill of frustration that comes with not having a proper understanding of your investment.

Years of trial and error and reverse engineering have led us to our current understanding. The power of our internal team of SEO nerds cannot be unlocked by any online course or “SEO plug-in” that you can consume.

Put another way, you wouldn’t give a salary of $120,000 or more much thought if you hired a full-time internal SEO expert. Why then do you hesitate to consider hiring a whole team whose sole purpose is to ensure the success of your company for as little as $6,000 per year?</p>
              <Div className="cs-height_45 cs-height_lg_30" />
            </Div>
            <Spacing lg='0' md='40'/>
          </Div>
          <Div className="col-lg-5 offset-xl-1">
            <Spacing lg='0' md='45'/>
            <Div className="cs-radius_15 cs-shine_hover_1">
              <Image src={graphic} alt="Service" className='cs-radius_15 w-100' width={800} height={600} />
            </Div>
          </Div>
        </Div>
      </Div>

      <Spacing lg='150' md='80'/>
      <Div className="container">
        <SectionHeading
          title='No Business Left Behind.' 
          subtitle='Pricing & Plans'
        />
        <Spacing lg='85' md='1'/>
        <PricingTableList/>
      </Div>

      {/* <Spacing lg='150' md='80'/>
      <TestimonialSlider /> */}
      <Spacing lg='145' md='80'/>
      <Div className="container cs-shape_wrap_4">
        <Div className="cs-shape_4"></Div>
        <Div className="cs-shape_4"></Div>
        <Div className="container">
          <Div className="row">
            <Div className="col-xl-5 col-lg-6">
              <SectionHeading
                title='Some pre questions and answers' 
                subtitle='FAQ’s'
              />
              <Spacing lg='90' md='45'/>
            </Div>
            <Div className="col-lg-6 offset-xl-1">
              <Accordion/>
            </Div>
          </Div>
        </Div>
      </Div>
      <Spacing lg="100" md="10" />
      <Div className= "cs-hidden_mobile"> 
      <MovingText2 data={serviceData2} />
      </Div>
      <Spacing lg='150' md='80'/>
      {/* Start CTA Section */}
      <Div className="container">
        <Cta
          title="Join the <u>Revolution</u>,<br/>Let's Innovate <u>Together</u>."
          btnText="Schedule a Call Today"
          btnLink="/contact"
          bgSrc={contactbg.src}
        />
      </Div>
      {/* End CTA Section */}
      </Layout>
    </>
  );
}
